spring.application.name=supemercado 

spring.datasource.url=jdbc:postgresql://localhost:5432/supemercado
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update